import { supabase } from "../lib/supabase";

// This page reads live from the database every time it loads.
export const dynamic = "force-dynamic";

const PATHWAY_STYLES = {
  "Certification Program": "bg-emerald-50 text-emerald-700 ring-emerald-100",
  "DBA": "bg-indigo-50 text-indigo-700 ring-indigo-100",
  "PhD": "bg-violet-50 text-violet-700 ring-violet-100",
  "Honorary Doctorate": "bg-amber-50 text-amber-700 ring-amber-100",
};

const GOAL_LABEL = {
  skill: "Build new skills",
  industry: "Industry leadership",
  research: "Research / academia",
  recognition: "Lifetime contribution",
};

export default async function SubmissionsPage() {
  const { data: rows, error } = await supabase
    .from("submissions")
    .select("*")
    .order("created_at", { ascending: false });

  const submissions = rows || [];

  // Summary metrics
  const total = submissions.length;
  const counts = {};
  let expSum = 0;
  submissions.forEach((s) => {
    counts[s.recommendation] = (counts[s.recommendation] || 0) + 1;
    expSum += s.experience_years || 0;
  });
  const topPathway = Object.keys(counts).sort((a, b) => counts[b] - counts[a])[0] || "—";
  const avgExp = total ? Math.round(expSum / total) : 0;

  return (
    <main className="min-h-screen bg-slate-50 text-slate-900">
      <div className="mx-auto max-w-5xl px-6 py-12">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">Submissions</h1>
            <p className="mt-1 text-sm text-slate-500">All recommendations generated by the engine.</p>
          </div>
          <a href="/" className="text-sm font-medium text-indigo-600 hover:text-indigo-700">
            &larr; Back to engine
          </a>
        </div>

        {error && (
          <div className="mt-6 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700 ring-1 ring-red-100">
            Could not load submissions.
          </div>
        )}

        {/* Summary metrics */}
        <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-3">
          <Metric label="Total submissions" value={total} />
          <Metric label="Top pathway" value={topPathway} />
          <Metric label="Avg. experience" value={`${avgExp} yrs`} />
        </div>

        {/* Table */}
        <div className="mt-8 overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-slate-100 bg-slate-50 text-slate-500">
                <th className="px-5 py-3 font-medium">Name</th>
                <th className="px-5 py-3 font-medium">Email</th>
                <th className="px-5 py-3 font-medium">Career goal</th>
                <th className="px-5 py-3 font-medium">Recommendation</th>
              </tr>
            </thead>
            <tbody>
              {submissions.length === 0 && (
                <tr>
                  <td colSpan={4} className="px-5 py-10 text-center text-slate-400">
                    No submissions yet.
                  </td>
                </tr>
              )}
              {submissions.map((s) => (
                <tr key={s.id} className="border-b border-slate-50 last:border-0 hover:bg-slate-50/60">
                  <td className="px-5 py-4 font-medium text-slate-800">{s.full_name}</td>
                  <td className="px-5 py-4 text-slate-500">{s.email}</td>
                  <td className="px-5 py-4 text-slate-600">{GOAL_LABEL[s.career_goal] || s.career_goal}</td>
                  <td className="px-5 py-4">
                    <span className={`rounded-full px-3 py-1 text-xs font-medium ring-1 ${PATHWAY_STYLES[s.recommendation] || "bg-slate-50 text-slate-600 ring-slate-100"}`}>
                      {s.recommendation}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </main>
  );
}

function Metric({ label, value }) {
  return (
    <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200">
      <p className="text-sm text-slate-500">{label}</p>
      <p className="mt-1 text-2xl font-semibold text-slate-900">{value}</p>
    </div>
  );
}